apiVersion: v1
kind: Service
metadata:
  name: joke-api-service
  labels:
    app: joke-api
spec:
  type: NodePort
  selector:
    app: joke-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080